name: vrc_manager
description: VRCManager

publish_to: "none"
version: 5.1.1+26

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^11.4.0
  domain_verification_manager: ^1.0.0
  flutter:
    sdk: flutter
  flutter_json_viewer: ^1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.12
  http: ^1.4.0
  intl: ^0.20.2
  logger: ^2.0.1
  package_info_plus: ^4.2.0
  flutter_sharing_intent: ^1.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  # Using flutter_inappwebview instead of webview_flutter
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  assets:
    - assets/svg/
  generate: true
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/icon.png"
