name: vrc_manager
description: VRCManager

publish_to: "none"
version: 5.0.3+24

environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.4
  device_info_plus: ^10.1.2
  domain_verification_manager: ^1.0.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.0+1
  flutter_json_viewer: ^1.0.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.6
  fluttertoast: ^8.0.9
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.0.1
  package_info_plus: ^8.0.2
  flutter_sharing_intent: ^1.1.1
  share_plus: ^10.0.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2
  webview_flutter: <4.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

flutter:
  assets:
    - assets/svg/
  generate: true
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/icon.png"
