Map<String, String> getVrchatLang() {
  return {
    "eng": "English",
    "kor": "한국어",
    "rus": "Русский",
    "spa": "Español",
    "por": "Português",
    "zho": "中文",
    "deu": "Deutsch",
    "jpn": "日本語",
    "fra": "Français",
    "swe": "Svenska",
    "nld": "Nederlands",
    "pol": "Polski",
    "dan": "Dansk",
    "nor": "Norsk",
    "ita": "Italiano",
    "tha": "ภาษาไทย",
    "fin": "Suomi",
    "hun": "Magyar",
    "ces": "Čeština",
    "tur": "Türkçe",
    "ara": "العربية",
    "ron": "Română",
    "vie": "Tiếng Việt",
    "ase": "American Sign Language",
    "bfi": "British Sign Language",
    "dse": "Dutch Sign Language",
    "fsl": "French Sign Language",
    "kvk": "Korean Sign Language",
  };
}
