name: "[ja] 🐛 バグを報告する"
description: vrc_managerの不具合を報告する。
labels: ["bug"]
body:

  - type: input
    id: os
    attributes:
      label: OS
      description: バージョンも含めてください
      placeholder: "例: Android 12, Window 10"
    validations:
      required: true

  - type: input
    id: device-name
    attributes:
      label: 端末名
      placeholder: "例: Samsung Galaxy S22 Ultra"
    validations:
      required: true

  - type: input
    id: country-of-origin
    attributes:
      label: 接続元の国名
      placeholder: "例: 日本"
    validations:
      required: true

  - type: dropdown
    id: download-location
    attributes:
      label: アプリをダウンロードした場所
      options:
        - Github(GMS)
        - Github(HMS)
        - Github(Windows)
        - Google Play Store
        - HUAWEI AppGallery
        - Xiaomi GetApps
        - Other
    validations:
      required: true

  - type: dropdown
    id: reinstall
    attributes:
      label: 再インストールしましたか？
      options:
        - はい
        - いいえ、恐らくその必要はない
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: 不具合の説明
      description: バグの内容を詳しく記述してください。期待される動作と実際の動作を含めてください。必要があれば画像を添付して下さい。
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 不具合を起こすための手順
      description: バグを発生させるための詳細な手順を記述してください。
      placeholder: |
        例:
          1. 「オンラインのフレンド」を開きます
          2. 表示設定を「デフォルト」から「シンプル」に変更します
          3. ...
          ...
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: エラーメッセージ
      description: エラーメッセージが表示されていればそれを貼り付けてください。
      render: shell
    validations:
      required: false
