name: "[ja] 💡 機能を提案する"
description: vrc_managerに欲しい機能を提案して下さい
labels: ["enhancement"]
body:

  - type: textarea
    id: feature-description
    attributes:
      label: 機能を説明する
    validations:
      required: true

  - type: textarea
    id: feature-reasoning
    attributes:
      label: この機能はユーザーにとってどのように役に立つのでしょうか？
    validations:
      required: true