name: "📓 Redirected from app"
description: Report error message in vrchat_mobile_client.
labels: ["bug"]
body:

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide detailed intructions to trigger the bug.
      placeholder: |
        Example:
          1. Start with all application data deleted.
          2. Login and open Home
          3. ...
          ...
    validations:
      required: true

  - type: dropdown
    id: download-location
    attributes:
      label: Where you downloaded the app
      options:
        - Github(GMS)
        - Github(HMS)
        - Github(Windows)
        - Google Play Store
        - HUAWEI AppGallery
        - Xiaomi GetApps
        - Other
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Relevant error message output
      description: Please paste the log. Logs are automatically copied to the clipboard.
      render: shell
    validations:
      required: true
